import numpy as np
import control as ct

from Models.BallBeam.StateSpace import LinearStateSpaceModel
from Models.BallBeam.NonlinearDynamics import NonlinearBallBeamModel
from Metrics_Plotting.SimLog import SimLog


class TFSimulator:
    """Calculates steps of a discrete transfer functions
    """
    ## simulates the trasfer function using difference:
    def __init__(self, tf, X_0):
        """Initialises the simulator from a discrete transfer function.

        Args:
            tf (ct.TransferFunction): Discrete transfer function generated by python-control.
            X_0 (float): Initial output value; used to pre-fill the output history.
        """
        self.num_dis = np.asarray(tf.num_list[0][0], dtype=float)
        self.den_dis = np.asarray(tf.den_list[0][0], dtype=float)

        self.u_hist = np.zeros(len(self.num_dis))

        # Initialize past outputs to zero. The current output history is built from
        # the discrete simulation as it advances, so prior outputs are assumed zero
        # unless the user supplies a more complete initial condition model.
        if len(self.den_dis) > 1:
            self.y_hist = np.zeros(len(self.den_dis) - 1)
        else:
            self.y_hist = np.array([])
    def reset(self, X_0):
        """Resets the internal state histories to zero, ready for a new simulation run.

        Args:
            X_0 (float): Initial output value (currently unused; histories are zeroed).
        """
        self.u_hist = np.zeros(len(self.num_dis))
        if len(self.den_dis) > 1:
            self.y_hist = np.zeros(len(self.den_dis)-1)
        else:
             self.y_hist = np.array([])
        
        return
    def step(self,u):
        """Calculates the next step y[k](y[k-1],y[k-2],....,u[k],u[k-1],...)

        Args:
            u (float): the input of the Transfer function

        Returns:
            y(float):the output of the Transfer function 
        """
        self.u_hist[1:] = self.u_hist[:-1]
        # all my elements exept the first one<= all my elements exept the last one 
        self.u_hist[0] = float(u)
        #strore first element

        y = np.dot(self.num_dis,self.u_hist)
        # dot product between the coeficients list and the u hist list 
        # implements b0u[k]+b1u[k-1].....
        y -= np.dot(self.den_dis[1:], self.y_hist)
        # dot product between the coeficients list and the u hist list 
        # implements a1y[k-1]+b2u[k-2].....

        y /= self.den_dis[0] # divide by a0 to get y[k]

        if len(self.y_hist) > 0:
            self.y_hist[1:] = self.y_hist[:-1]
            self.y_hist[0] = y

        
        #all my elements exept the first one<= all my elements exept the last one 
        
        #strore first element

        return y
class HybridSim:
    """Provides the tools for the setup and simulation of a discrete controller and a continuous plant
    """
    def __init__(self, StateSpaceModel: LinearStateSpaceModel, config_file):
        """Initialises the hybrid simulator with a continuous state-space plant.

        Args:
            StateSpaceModel (LinearStateSpaceModel): Provides the A, B, C matrices
                of the linearised continuous plant.
            config_file: Plant configuration module; must expose ``T`` (total simulation
                time in seconds) and ``dt`` (controller sampling period in seconds).
        """
        self.dt_plant=1e-3
        ## state space models
        self.A=StateSpaceModel.A.astype(float)
        self.B=StateSpaceModel.B.astype(float)
        self.C=StateSpaceModel.C.astype(float)
        ##
        self.config_file=config_file
        ##
        return
   
    def rk4_step(self, X, u_k):
        """Advances the continuous state one integration step using RK4.

        Args:
            X (np.ndarray): Current state vector X[k].
            u_k (np.ndarray): Control input applied during this step.

        Returns:
            np.ndarray: Updated state vector X[k+1].
        """
        
        def function(X):
            """space state derivative calculation 

            Args:
                X (_type_): the vector

            Returns:
                _type_: the derivative
            """
            return self.A @ X + self.B @ u_k 
        k1=function(X)
        k2=function(X+self.dt_plant*0.5*k1)
        k3=function(X+0.5*self.dt_plant*k2)
        k4=function(X+self.dt_plant*k3)
        
        return X +self.dt_plant/6*(k1+2*k2+2*k3+k4)
class NonLinearHybridSim:
    def __init__(self, model: NonlinearBallBeamModel, config_file):
        self.dynamics = model.f
        self.C = np.array([[1, 0]])   # C matrix 
        self.dt_plant = 1e-3          # for RK4
        self.config_file = config_file
        
    def rk4_step(self, X, u_k) -> np.ndarray:
        u = float(np.squeeze(u_k))
        f = self.dynamics
        k1 = f(X, u)
        k2 = f(X + self.dt_plant * 0.5 * k1, u)
        k3 = f(X + 0.5 * self.dt_plant * k2, u)
        k4 = f(X + self.dt_plant * k3, u)
        return X + self.dt_plant / 6 * (k1 + 2*k2 + 2*k3 + k4)
